version: "3.3"
services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_DATABASE=alinfo
    ports:
      - 3306:3306
    volumes:
      - './.mysql-data/db:/var/lib/mysql'
    networks:
      - projectdevops
  app:
    depends_on:
      - mysqldb
    image: sawsanselmi/tpachat:46
    restart: on-failure
    networks:
      - projectdevops
    ports:
      - 8089:8089
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/alinfo?useSSL=false",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"}'
